package com.ryderbelserion.laser.core.api.message.context;

import org.jspecify.annotations.NonNull;

@FunctionalInterface
public interface MessageResolver<S, C extends MessageContext> {

    /**
     * Resolves the message, in most cases it'll send the message to the sender.
     *
     * @param sender  The command sender.
     * @param context The {@link MessageContext} generated by the command executor.
     */
    void resolve(@NonNull final S sender, @NonNull final C context);

}